config/routes.rb
Rails.application.routes.draw do
  resources :barmen
  resources :stocks
  resources :cashboxes
  root 'application#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/barman.rb
class Barman < ApplicationRecord
    validates :name, :age, :salary, presence:true
    validates :salary, numericality: {greater_than_or_equal_to: 0}
    validates :age, numericality: {in: 18..65}
    validates :name, length: {minimum: 2}

    def to_s
        return "Barman " + name + ", age: " + age.to_s + ", salary: " + salary.to_s
    end

end

app/models/cashbox.rb
class Cashbox < ApplicationRecord
    validates :money, presence: true
    validates :money, numericality: {greater_than_or_equal_to: 0}

    def to_s
        return "Cashbox amount: " + money.to_s
    end
end

app/models/stock.rb
class Stock < ApplicationRecord
        validates :brownies, :donuts, :milk, :sugar, :coffee, numericality: {greater_than_or_equal_to: 0}
        validates :brownies, :donuts, :milk, :sugar, :coffee, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/barmen_controller.rb
class BarmenController < ApplicationController
  before_action :set_barman, only: %i[ show edit update destroy ]

  # GET /barmen or /barmen.json
  def index
    @barmen = Barman.all
  end

  # GET /barmen/1 or /barmen/1.json
  def show
  end

  # GET /barmen/new
  def new
    @barman = Barman.new
  end

  # GET /barmen/1/edit
  def edit
  end

  # POST /barmen or /barmen.json
  def create
    @barman = Barman.new(barman_params)

    respond_to do |format|
      if @barman.save
        format.html { redirect_to barman_url(@barman), notice: "Barman was successfully created." }
        format.json { render :show, status: :created, location: @barman }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @barman.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barmen/1 or /barmen/1.json
  def update
    respond_to do |format|
      if @barman.update(barman_params)
        format.html { redirect_to barman_url(@barman), notice: "Barman was successfully updated." }
        format.json { render :show, status: :ok, location: @barman }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @barman.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barmen/1 or /barmen/1.json
  def destroy
    @barman.destroy

    respond_to do |format|
      format.html { redirect_to barmen_url, notice: "Barman was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barman
      @barman = Barman.find(params.permit(:id)[:id].to_i)
    end

    # Only allow a list of trusted parameters through.
    def barman_params
      params.require(:barman).permit(:name, :salary, :age)
    end
end

app/controllers/cashboxes_controller.rb
class CashboxesController < ApplicationController
  before_action :set_cashbox, only: %i[ show edit update destroy ]

  # GET /cashboxes or /cashboxes.json
  def index
    @cashboxes = Cashbox.all
  end

  # GET /cashboxes/1 or /cashboxes/1.json
  def show
  end

  # GET /cashboxes/new
  def new
    @cashbox = Cashbox.new
  end

  # GET /cashboxes/1/edit
  def edit
  end

  # POST /cashboxes or /cashboxes.json
  def create
    @cashbox = Cashbox.new(cashbox_params)

    respond_to do |format|
      if @cashbox.save
        format.html { redirect_to cashbox_url(@cashbox), notice: "Cashbox was successfully created." }
        format.json { render :show, status: :created, location: @cashbox }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cashbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cashboxes/1 or /cashboxes/1.json
  def update
    respond_to do |format|
      if @cashbox.update(cashbox_params)
        format.html { redirect_to cashbox_url(@cashbox), notice: "Cashbox was successfully updated." }
        format.json { render :show, status: :ok, location: @cashbox }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cashbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cashboxes/1 or /cashboxes/1.json
  def destroy
    @cashbox.destroy

    respond_to do |format|
      format.html { redirect_to cashboxes_url, notice: "Cashbox was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cashbox
      @cashbox = Cashbox.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cashbox_params
      params.require(:cashbox).permit(:money)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create

    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:brownies, :donuts, :milk, :coffee, :sugar)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barmen_helper.rb
module BarmenHelper
end

app/helpers/cashboxes_helper.rb
module CashboxesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/index.html.erb
<% @barmen = Barman.all%>
<%= render partial: 'barmen/index', object: @barmen %>

<% @stocks = Stock.all%>
<%= render partial: 'stocks/index', object: @stocks %>

<% @cashboxes = Cashbox.all%>
<%= render partial: 'cashboxes/index', object: @cashboxes %>

app/views/barmen/_barman.html.erb
<div id="<%= dom_id barman %>">
  <p>
    <strong>Name:</strong>
    <%= barman.name %>
  </p>
    <p>
    <strong>Age:</strong>
    <%= barman.age %>
  </p>
    <p>
    <strong>Salary:</strong>
    <%= barman.salary %>
  </p>

</div>

app/views/barmen/_edit.html.erb
<h1>Editing barman</h1>

<%= render "form", barman: @barman %>

<br>

<div>
  <%= link_to "Show this barman", @barman %> |
  <%= link_to "Back to barmen", barmen_path %>
</div>

app/views/barmen/_form.html.erb
<%= form_with(model: barman) do |form| %>
  <% if barman.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(barman.errors.count, "error") %> prohibited this barman from being saved:</h2>

      <ul>
        <% barman.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
    <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>
    <div>
    <%= form.label :salary, style: "display: block" %>
    <%= form.number_field :salary %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %> 

app/views/barmen/_index.html.erb
<p style="color: green"><%= notice %></p>

<h4>Barmen:</h4>

<%= render @barmen%>

app/views/barmen/_show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @barman %>

<div>
  <%= link_to "Edit this barman", edit_barman_path(@barman) %> |
  <%= link_to "Back to barmen", barmen_path %>

  <%= button_to "Destroy this barman", @barman, method: :delete %>
</div>

app/views/barmen/edit.html.erb
<h1>Editing barman</h1>

<%= render "form", barman: @barman %>

<br>

<div>
  <%= link_to "Show this barman", @barman %> |
  <%= link_to "Back to barmen", barmen_path %>
</div>

app/views/barmen/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Barmen</h1>

<div id="barmen">
  <% @barmen.each do |barman| %>
    <%= render barman %>
    <p>
      <%= link_to "Show this barman", barman %>
    </p>
  <% end %>
</div>

<%= link_to "New barman", new_barman_path %>

app/views/barmen/new.html.erb
<h1>New barman</h1>

<%= render "form", barman: @barman %>

<br>

<div>
  <%= link_to "Back to barmen", barmen_path %>
</div>

app/views/barmen/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @barman %>

<div>
  <%= link_to "Edit this barman", edit_barman_path(@barman) %> |
  <%= link_to "Back to barmen", barmen_path %>

  <%= button_to "Destroy this barman", @barman, method: :delete %>
</div>

app/views/cashboxes/_cashbox.html.erb
<div id="<%= dom_id cashbox %>">
  <p>
    <strong>Money:</strong>
    <%= cashbox.money %>
  </p>

</div>

app/views/cashboxes/_form.html.erb
<%= form_with(model: cashbox) do |form| %>
  <% if cashbox.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cashbox.errors.count, "error") %> prohibited this cashbox from being saved:</h2>

      <ul>
        <% cashbox.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :money, style: "display: block" %>
    <%= form.number_field :money %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cashboxes/_index.html.erb
<p style="color: green"><%= notice %></p>

<h4>Cashboxes:</h4>

<%= render @cashboxes%>

app/views/cashboxes/edit.html.erb
<h1>Editing cashbox</h1>

<%= render "form", cashbox: @cashbox %>

<br>

<div>
  <%= link_to "Show this cashbox", @cashbox %> |
  <%= link_to "Back to cashboxes", cashboxes_path %>
</div>

app/views/cashboxes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cashboxes</h1>

<div id="cashboxes">
  <% @cashboxes.each do |cashbox| %>
    <%= render cashbox %>
    <p>
      <%= link_to "Show this cashbox", cashbox %>
    </p>
  <% end %>
</div>

<%= link_to "New cashbox", new_cashbox_path %>

app/views/cashboxes/new.html.erb
<h1>New cashbox</h1>

<%= render "form", cashbox: @cashbox %>

<br>

<div>
  <%= link_to "Back to cashboxes", cashboxes_path %>
</div>

app/views/cashboxes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cashbox %>

<div>
  <%= link_to "Edit this cashbox", edit_cashbox_path(@cashbox) %> |
  <%= link_to "Back to cashboxes", cashboxes_path %>

  <%= button_to "Destroy this cashbox", @cashbox, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TCafe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag asset_path('favicon-16x16.png') %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': 'reload'%>
    <%= stylesheet_pack_tag "application", media: 'all', 'data-turbolinks-track': 'reload'%>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">TCafe</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href= <%=barmen_url%> >Barmen</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href= <%=stocks_url%> >Stocks</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href= <%=cashboxes_url%> >Cashboxes</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="content">
      <%= yield %>
    </div>

    <footer class="bg-dark text-center text-lg-start fixed-bottom">
      <!-- Copyright -->
      <div class="text-center p-3" style = "background-color: #212529;">
        <a class="navbar-brand" href="/" style="color: #ffffff" >TCafe</a>
      </div>
      <!-- Copyright -->
    </footer>
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock) do |form| %>
  <% if stock.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :brownies, style: "display: block" %>
    <%= form.number_field :brownies %>
  </div>

  <div>
    <%= form.label :donuts, style: "display: block" %>
    <%= form.number_field :donuts %>
  </div>

  <div>
    <%= form.label :milk, style: "display: block" %>
    <%= form.number_field :milk %>
  </div>

  <div>
    <%= form.label :coffee, style: "display: block" %>
    <%= form.number_field :coffee %>
  </div>

  <div>
    <%= form.label :sugar, style: "display: block" %>
    <%= form.number_field :sugar %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/_index.html.erb
<p style="color: green"><%= notice %></p>

<h4>Stocks:</h4>

<%= render @stocks%>

app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">
  <p>
    <strong>Brownie:</strong>
    <%= stock.brownies %>
  </p>

  <p>
    <strong>Donut:</strong>
    <%= stock.donuts %>
  </p>

  <p>
    <strong>Milk:</strong>
    <%= stock.milk %>
  </p>

  <p>
    <strong>Coffee:</strong>
    <%= stock.coffee %>
  </p>

  <p>
    <strong>Sugar:</strong>
    <%= stock.sugar %>
  </p>

</div>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Show this stock", @stock %> |
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stocks</h1>

<div id="stocks">
  <% @stocks.each do |stock| %>
    <%= render stock %>
    <p>
      <%= link_to "Show this stock", stock %>
    </p>
  <% end %>
</div>

<%= link_to "New stock", new_stock_path %>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @stock %>

<div>
  <%= link_to "Edit this stock", edit_stock_path(@stock) %> |
  <%= link_to "Back to stocks", stocks_path %>

  <%= button_to "Destroy this stock", @stock, method: :delete %>
</div>

app/views/welcome/index.html.erb
<h2>TCafe</h2>

<a href = <%=barmen_path%>>Barmen<br></a>
<a href = <%=cashboxes_path%>>Cashboxes<br></a>
<a href = <%=stocks_path%>>Stocks</a>